# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-04 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20180601_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseresource',
            old_name='dowmload',
            new_name='download',
        ),
    ]
